In [17]:
from sklearn import datasets
from sklearn.svm import SVC
from scipy import misc
import numpy as np

In [18]:
digits=datasets.load_digits()
print(digits)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [19]:
features=digits.data
labels=digits.target
print(features,labels)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]] [0 1 2 ... 8 9 8]


In [20]:
clf=SVC(gamma=0.001)
clf.fit(features,labels)
print(clf.predict([features[-2]]))

[9]


In [24]:
img=misc.imread("test_data/img.jpg")
img=misc.imresize(img,(8,8))
img=img.astype(digits.images.dtype)
img=img.bytescale(img,high=16,low=0)
print
print(img.dtype)

float64


C:\Users\pkumar24\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """Entry point for launching an IPython kernel.
C:\Users\pkumar24\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  


In [23]:
print(img)


[[[ 0  0  0]
  [ 4  4  4]
  [14 14 14]
  [ 6  6  6]
  [ 8  8  8]
  [ 7  7  7]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 8  8  8]
  [ 5  5  5]
  [ 2  2  2]
  [10 10 10]
  [ 3  3  3]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 3  3  3]
  [13 13 13]
  [16 16 16]
  [ 4  4  4]
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 2  2  2]
  [11 11 11]
  [ 9  9  9]
  [10 10 10]
  [ 3  3  3]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 6  6  6]
  [ 5  5  5]
  [ 0  0  0]
  [ 3  3  3]
  [10 10 10]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 5  5  5]
  [ 6  6  6]
  [ 0  0  0]
  [ 0  0  0]
  [10 10 10]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 2  2  2]
  [10 10 10]
  [ 6  6  6]
  [ 5  5  5]
  [ 9  9  9]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 2  2  2]
  [ 7  7  7]
  [ 7  7  7]
  [ 2  2  2]
  [ 0  0  0]
  [ 0  0  0]]]
